version: '3'
services:
  app-mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db_data01:/var/lib/mysql
      - "./db/script/setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    environment:
      MYSQL_DATABASE: '$MYSQLDB_DATABASE'
      MYSQL_ROOT_PASSWORD: '$MYSQLDB_PASSWORD'
    ports:
      - $MYSQLDB_Host_PORT:$MYSQLDB_PORT
  java-app:
   build:
    context: .
    dockerfile: Dockerfile
   ports:
    - "8081:8080"
   restart: always
   environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://app-mysql:$MYSQLDB_PORT/$MYSQLDB_DATABASE?createDatabaseIfNotExist=true
        SPRING_DATASOURCE_USERNAME: '$MYSQLDB_USER'
        SPRING_DATASOURCE_PASSWORD: '$MYSQLDB_PASSWORD'
   depends_on:
      - app-mysql
volumes:
     db_data01:
