version: '3'
services:
  app-mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    #  command:  --disable-partition-engine-check
    restart: always
    volumes:
      - db_data01:/var/lib/mysql
      - "./db/script/setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    environment:
      MYSQL_DATABASE: springboot_mysql_example
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  java-app:
   build:
    context: .
    dockerfile: Dockerfile
   ports:
    - "8081:8080"
   restart: always
   environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://app-mysql:3306/springboot_mysql_example?createDatabaseIfNotExist=true
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root
   depends_on:
      - app-mysql
volumes:
     db_data01:
